=== YuliaMelnyk/Series/Example.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="movies">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="series"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="series">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="serie"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="serie">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="id"/>
                <xs:element ref="name"/>
                <xs:element ref="country"/>
                <xs:element ref="desc"/>
                <xs:element ref="genre"/>
                <xs:element ref="notes"/>
                <xs:element ref="images"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="id" type="xs:integer"/>
    <xs:element name="name" type="xs:string"/>
    <xs:element name="country" type="xs:NCName"/>
    <xs:element name="desc">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="title"/>
                <xs:element ref="en"/>
                <xs:element ref="es"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="title" type="xs:string"/>
    <xs:element name="en" type="xs:string"/>
    <xs:element name="es" type="xs:string"/>
    <xs:element name="genre" type="xs:NCName"/>
    <xs:element name="notes" type="xs:string"/>
    <xs:element name="images">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="image"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="image">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="url"/>
            </xs:sequence>
            <xs:attribute name="id" use="required" type="xs:integer"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="url" type="xs:anyURI"/>
</xs:schema>

=== YuliaMelnyk/Series/Example.xml
<?xml version="1.0" encoding="utf-8"?>
<movies xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///C:/xampp/htdocs/proyecto/series/Example.xsd">
	<series>
<serie>
<id>1</id>
<name>Devs</name>
<country>USA</country>
<desc>
	<title>
		Alex Garland Wants to Break Your Brain with the Brilliant Devs
	</title>
<en>The genius behind “Ex Machina” and “Annihilation” brings his brand of highly philosophical and intellectual sci-fi to the new ‘FX on Hulu’ section this week with the stunningly ambitious “Devs,” a great show that’s almost impossible to write about in a review. Like he did in his last two films, Alex Garland unpacks his themes slowly and deliberately, not revealing what “Devs” is primarily about until several episodes in. Not only do we not have a habit on this site of spoiling anything major that happens after a series premiere, but FX has been insistent about not revealing what this show really becomes. All I’ll say is that it’s a daring and new deconstruction of one of the basic tenets of human existence. At times throughout the season, Garland’s tendency to direct actors to affectless, almost monotonous performances will push casual viewers away, but I plead patience here. It’s ultimately an unforgettable and rewarding experience, and one that I really hope people are talking about and writing about once everything has been put on the table.
            Lily Chan (Sonoya Mizuno, who was Oscar Isaac’s dance partner in “Ex Machina”) is a software engineer at a company called Amaya, run by the mysterious Forest (Nick Offerman). Amaya is like any number of Silicon Valley companies trying to do something that the rest of the competition in the tech sector isn’t even considering. There’s an elite branch of Amaya called “Devs,” and Lily’s boyfriend Sergei (Karl Glusman) is basically promoted to that exclusive department in the premiere. He goes to work in Devs, meeting fellow elites like the mysterious Katie (Alison Pill) and kindly Stewart (Stephen McKinley Henderson), but only after a serious grilling by security head Kenton (Zach Grenier). After his first day in Devs, Sergei disappears, and the show becomes Lily’s story, trying to figure out what exactly happened to her boyfriend and how it's related to what they do in Devs.
            We know the answer to the first question when it happens but the exact nature of the tech research in Devs unfolds slowly, dominating the mystery of the first half of the season. And it does so in a manner that feels more like a ‘70s conspiracy thriller than a traditional sci-fi film. There are covert meetings with dangerous people under bridges and in parking garages, and bursts of shocking violence in “Devs.” Garland has a storytelling model and Lily is cut from the same cloth as Domhnall Gleeson’s character in “Ex Machina” and Natalie Portman’s in “Annihilation,” the observer who then changes what’s being observed. He’s fascinated by human interaction with technology but not in a cold, observant way. There’s a push and pull between individuality and determinism in all of his work, and he digs deep into how systems are shaped by human input, need, and emotion.

            Clearly, there’s a lot to chew on in “Devs,” but some of the performances can feel a bit overly familiar. Offerman gets better but starts the season as a bit of a tech messiah archetype that we’ve seen before. He’s a character meant to hold so many secrets as to his purpose in the first few episodes that his mysterious nature almost tends to parody. Similarly, Mizuno feels like a blank slate early in the season but she’s asked to do a lot in the back half of the year and she ultimately worked for me. What I liked most about the cast of “Devs” is how much Garland chose to work with a very tight ensemble. A lot of creators think high-concept TV means dozens of arcs, subplots, and speaking roles—“Westworld” often fell victim to this—but “Devs” is comparatively focused, allowing Garland, who wrote and directed every episode, to really sketch out each of his speaking roles into interesting characters.
            “Devs” also simply looks better than most modern television, shot by Garland’s regular collaborator Rob Hardy. Working with Garland, they give the show a much warmer, denser color palette than it would have had in other hands. Even the production design of the Devs building fascinated me with its undeniably futuristic look that is also balanced by warm colors, which makes more sense when one learns Forest’s grand plan. It’s that kind of show, one in which design and visual choices were clearly influenced by theme and plot instead of merely functional. It’s a show that’s as constantly surprising in its artistic choices—for example, how an early fight scene is staged is startling—as it is in its narrative. It feels constantly just left-of-center, even when it’s treading familiar sci-fi ground.

            There’s a scene late in the season in which Forest mentions how every generation seems to be speeding up development. For generations, we were happy in caves, painting on the walls. Now, there’s a new way to communicate and comprehend the world every few hours. Alex Garland wants to question and confront what this acceleration means for the human race. And he’s done so with one of the best new shows in a long time.
</en>
<es>Spanish description</es>
</desc>
<genre>drama</genre>
<notes>Private notes</notes>
<images>
<image id="1">
<url> https://static.rogerebert.com/uploads/blog_post/primary_image/streaming/alex-garland-wants-to-break-your-brain-with-the-brilliant-devs/01_Sonoya_Actor_spread_re.01_copy.jpg</url>
</image>
<image id="2">
<url> https://static.rogerebert.com/uploads/blog_post/primary_image/streaming/alex-garland-wants-to-break-your-brain-with-the-brilliant-devs/01_Sonoya_Actor_spread_re.01_copy.jpg</url>
</image>
<image id="3">
<url> https://static.rogerebert.com/uploads/blog_post/primary_image/streaming/alex-garland-wants-to-break-your-brain-with-the-brilliant-devs/01_Sonoya_Actor_spread_re.01_copy.jpg</url>
</image>
</images>
</serie>
<serie>
<id>2</id>
<name>Little Fires Everywhere</name>
<country>USA</country>
<desc>
	<title>
		'Little Fires Everywhere' Finds Families Ready To Collide
	</title>
<en>The great frustration of Little Fires Everywhere, the Hulu adaptation of Celeste Ng's popular novel, is that of the eight episodes, they only made seven available for review.

            It matters because Little Fires Everywhere is a story of collision. Mia (Kerry Washington) and her daughter Pearl (Lexi Underwood), temporarily living in their car, come to Shaker Heights, Ohio. They collide with the wealthy Elena Richardson (Reese Witherspoon), who has a house to rent. Mia and Pearl become entangled with Elena and her husband and four children, and eventually, even their friends can't avoid each other.
            
            Those who have seen Big Little Lies will recognize Elena as a more malevolent version of the wealthy, driven, status-obsessed mother Witherspoon she plays there. Ohio and not Monterey, and yet recognizably similar. Those who have seen Scandal may even recognize Mia as a much less well-connected version of the driven survivor Washington plays there. Putting the very different energies of these actresses in conversation with each other is a good, promising idea.

            Much of the story also takes place in the complex emotional lives of Elena and Mia's children. In particular, Mia worries over the attachment Pearl quickly forms to the Richardsons, and to their nice big house and their leisure time and their stability. Elena is baffled by her youngest, a budding artist and raw nerve named Izzy (Megan Stott), who gravitates toward Mia, both because she's an artist and because she's almost as skeptical of Elena as Izzy is.

The series doesn't quite feel solid, in part because as it progresses, Elena becomes more unambiguously awful. It's a better show when it feels like two very different mothers with very different cards to play, trying in their own ways to offer the parenting they think is needed. But a plot development involving a co-worker of Mia's and a friend of Elena's winds up unbalancing their relationship. While this creates a certain tension, it's hard to know whether that tension will find any resolution.

But again, this is the frustration: The point is that the first seven episodes build and build the pressure on and among all these characters and the worlds they inhabit. Pearl and Izzy feel rejected by their mothers; Elena and Mia feel pushed away by their daughters. Elena's other daughter Lexi is pushed to confront her own privilege, while her brothers Trip and Moody have different attachments to Pearl and different ways of treating her well and poorly. It builds and builds, and either the series sticks the landing in that last episode and it feels worth the ride, or it doesn't, and it doesn't.

With some series, this feels less important. In some cases, the pleasures of a show are such that there's less of a nagging concern over whether it will successfully tie itself together. But this one feels just unsteady enough that if it doesn't land on a coherent final chord, it won't hold together as a whole. The caliber of performers and the strength of the source material makes me optimistic. But in a series about collision, not getting to see what happens when everything collides makes it hard to feel like you've seen it at all.
</en>
<es>Spanish description</es>
</desc>
<genre>drama</genre>
<notes>Private notes</notes>
<images>
<image id="1">
<url>https://media.npr.org/assets/img/2020/03/17/littlefires_wide-4f523b60da8810925da3252cc120b1f56b38bff6-s1600-c85.jpg</url>
</image>
<image id="2">
<url>https://media.npr.org/assets/img/2020/03/17/littlefires_wide-4f523b60da8810925da3252cc120b1f56b38bff6-s1600-c85.jpg</url>
</image>
<image id="3">
